export default {
  DeleteProduct: "https://chippisoft.com/API/Deleteproduct.php",
  DeleteCategories: "https://chippisoft.com/API/Deletecategories.php",
  UpdateCategories: "https://chippisoft.com/API/Updatecategories.php",
  ListProduct: "https://chippisoft.com/API/Getallproducts.php?page=",
  GetTransaction: "https://chippisoft.com/API/Transaction.php",
  GetMemberCount: "https://chippisoft.com/API/Countmember.php",
  GetTotalIncome: "https://chippisoft.com/API/Countmoney.php",
  GetCategories: "https://chippisoft.com/API/Categories.php",
  ProductDetail: "https://chippisoft.com/API/Product.php",
  AddCategory: "https://chippisoft.com/API/Addcategories.php",
  AddProduct: "https://chippisoft.com/API/Addnewproduct.php",
  UpdateProduct: "https://chippisoft.com/API/Updateproduct.php",
  SoftwareSold: "https://chippisoft.com/API/Countlicense.php",
  ChangeBalance: "https://chippisoft.com/API/Changebalance.php",
  MemberList: "https://chippisoft.com/API/Getallusers.php",
  DeleteMember: "https://chippisoft.com/API/Deleteuser.php",
};
